### ISSUE TITLE
Document the bundles

### ISSUE THREAD

**Issue by Nyholm** [php-cache/documentation#3]
Should we include documentation for the bundles in the docs?
I believe that the adapters and common libraries will have a stable API once we reach 1.0. I'm not sure that is the case for the bundles. They will change with Symfony and documentation is also likely to change. It would be more difficult to version the API with those bundles. 

I think it is better to leave the docs for the bundles at GitHub and later (if we want to) move them to a subdomain of php-cache.com.

**Comment by aequasi** [comment]
I honestly think there should be a one stop shop for documentation, like
JMS has

A. Scherer

**Comment by Nyholm** [comment]
I copied the bundle documentation. https://github.com/php-cache/documentation/commit/949ac4297a97c32c231093855f502a1420807eb8

We need to review and correct/unify/update all our docs at a later stage.
