### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by Nyholm** [php-cache/documentation#9]
The current logo is stolen from internet. We need to create our own. All suggestions are welcome. It could be something really abstract like [Stash](www.stashphp.com).

**Comment by aequasi** [comment]
Agreed, any ideas?

**Comment by Nyholm** [comment]
Sorry no. This is really far from my expertise. Ivebeen googling "cache" but I have not found any common symbol. (Compared to when you google "database")

At aequasi cache bundle you have a double play button in the toolbar. Did you make that yourself?

**Comment by aequasi** [comment]
i did not
